// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID            int32
	Name          string
	KeyString     string
	UserID        pgtype.Int4
	OrderID       pgtype.Text
	ProductID     pgtype.Int4
	TierLevel     pgtype.Int4
	QuotaLimit    pgtype.Int8
	QuotaUsed     pgtype.Int8
	AllowedModels []byte
	Status        pgtype.Int4
	CreatedAt     pgtype.Timestamptz
}

type AsyncTask struct {
	ID               string
	UserID           int32
	ChannelID        pgtype.Int4
	RequestID        string
	TaskType         string
	Provider         string
	ModelName        string
	Status           string
	UpstreamTaskID   pgtype.Text
	InputPayload     []byte
	OutputPayload    []byte
	ErrorPayload     []byte
	Metadata         []byte
	PreDeductedCents int64
	GrantDeducted    int64
	CashDeducted     int64
	ActualCostCents  int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	SubmittedAt      pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	CanceledAt       pgtype.Timestamptz
}

type BalanceLog struct {
	ID                 int64
	TransactionID      pgtype.Int8
	UserID             int32
	BalanceType        string
	ActionType         string
	AmountCents        int64
	BeforeBalanceCents int64
	AfterBalanceCents  int64
	OperatorAdminID    pgtype.Int4
	OperatorName       string
	Remark             string
	CreatedAt          pgtype.Timestamptz
}

type BillingLog struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	RequestID        pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type BillingLogs202604 struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	RequestID        pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type BillingLogs202605 struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	RequestID        pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type BillingLogs202606 struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	RequestID        pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type BillingLogs202607 struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	RequestID        pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type BillingLogs202608 struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	RequestID        pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type BillingLogs202609 struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	RequestID        pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type BillingLogs202610 struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	RequestID        pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type BillingLogs202611 struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	RequestID        pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type BillingLogs202612 struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	RequestID        pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type Channel struct {
	ID            int32
	Name          string
	Provider      string
	BaseUrl       string
	ApiKey        string
	Models        string
	ProtocolType  string
	UploadMode    string
	ModelMapping  []byte
	SupportsAsync bool
	Weight        pgtype.Int4
	Status        pgtype.Int4
}

type Model struct {
	ID                  int32
	ModelName           string
	InputPriceCents     int64
	OutputPriceCents    int64
	CacheHitPriceCents  int64
	CacheMissPriceCents int64
	Multiplier          float32
	BillingPolicy       string
	Modality            string
	PricingMode         string
	PricingConfig       []byte
	MaxConcurrency      int32
	Status              pgtype.Int4
}

type Transaction struct {
	ID                 int64
	UserID             int32
	EventID            pgtype.Text
	Type               string
	BalanceType        string
	Direction          string
	AmountCents        int64
	BeforeBalanceCents int64
	AfterBalanceCents  int64
	SourceType         string
	SourceID           string
	Status             string
	Remark             string
	Metadata           []byte
	CreatedAt          pgtype.Timestamptz
}

type User struct {
	ID             int32
	Email          string
	PasswordHash   string
	Nickname       pgtype.Text
	AvatarUrl      pgtype.Text
	CashBalance    pgtype.Int8
	GrantBalance   pgtype.Int8
	TierLevel      pgtype.Int4
	GrantExpiresAt pgtype.Timestamptz
	Status         pgtype.Int4
	LastLoginAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}
