// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkBillingLogExists = `-- name: CheckBillingLogExists :one
SELECT EXISTS (
        SELECT 1
        FROM billing_logs
        WHERE
            request_id = $1
    )
`

func (q *Queries) CheckBillingLogExists(ctx context.Context, requestID pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkBillingLogExists, requestID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countActiveUserAPIKeys = `-- name: CountActiveUserAPIKeys :one
SELECT COUNT(*) FROM api_keys WHERE user_id = $1 AND status = 1
`

func (q *Queries) CountActiveUserAPIKeys(ctx context.Context, userID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUserAPIKeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBillingLogs = `-- name: CountBillingLogs :one
SELECT COUNT(*) FROM billing_logs
`

func (q *Queries) CountBillingLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBillingLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserBillingLogs = `-- name: CountUserBillingLogs :one
SELECT COUNT(*)
FROM billing_logs
WHERE user_id = $1
  AND ($2::varchar = '' OR model_name = $2)
  AND created_at >= $3
`

type CountUserBillingLogsParams struct {
	UserID    pgtype.Int4
	ModelName string
	StartTime pgtype.Timestamptz
}

func (q *Queries) CountUserBillingLogs(ctx context.Context, arg CountUserBillingLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserBillingLogs, arg.UserID, arg.ModelName, arg.StartTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    name,
    key_string,
    user_id,
    allowed_models,
    status,
    tier_level
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, key_string, allowed_models, status, created_at
`

type CreateAPIKeyParams struct {
	Name          string
	KeyString     string
	UserID        pgtype.Int4
	AllowedModels []byte
	Status        pgtype.Int4
	TierLevel     pgtype.Int4
}

type CreateAPIKeyRow struct {
	ID            int32
	Name          string
	KeyString     string
	AllowedModels []byte
	Status        pgtype.Int4
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.KeyString,
		arg.UserID,
		arg.AllowedModels,
		arg.Status,
		arg.TierLevel,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyString,
		&i.AllowedModels,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createBillingLog = `-- name: CreateBillingLog :one
INSERT INTO
    billing_logs (
        id,
        user_id,
        channel_id,
        model_name,
        prompt_tokens,
        completion_tokens,
        cache_hit_tokens,
        cache_miss_tokens,
        amount_cents,
        request_id
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10
    ) RETURNING id, user_id, channel_id, model_name, prompt_tokens, completion_tokens, cache_hit_tokens, cache_miss_tokens, amount_cents, request_id, created_at
`

type CreateBillingLogParams struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	RequestID        pgtype.Text
}

func (q *Queries) CreateBillingLog(ctx context.Context, arg CreateBillingLogParams) (BillingLog, error) {
	row := q.db.QueryRow(ctx, createBillingLog,
		arg.ID,
		arg.UserID,
		arg.ChannelID,
		arg.ModelName,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CacheHitTokens,
		arg.CacheMissTokens,
		arg.AmountCents,
		arg.RequestID,
	)
	var i BillingLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.ModelName,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CacheHitTokens,
		&i.CacheMissTokens,
		&i.AmountCents,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const createChannel = `-- name: CreateChannel :one

INSERT INTO
    channels (
        name,
        provider,
        base_url,
        api_key,
        weight,
        models,
        status
    )
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, provider, base_url, api_key, models, weight, status
`

type CreateChannelParams struct {
	Name     string
	Provider string
	BaseUrl  string
	ApiKey   string
	Weight   pgtype.Int4
	Models   string
	Status   pgtype.Int4
}

// ==========================================
// Admin API Queries (Admin Panel CRUD)
// ==========================================
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.Provider,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Weight,
		arg.Models,
		arg.Status,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.Weight,
		&i.Status,
	)
	return i, err
}

const createModel = `-- name: CreateModel :one
INSERT INTO
    models (
        model_name,
        input_price_cents,
        output_price_cents,
        cache_hit_price_cents,
        cache_miss_price_cents,
        multiplier,
        status
    )
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, model_name, input_price_cents, output_price_cents, cache_hit_price_cents, cache_miss_price_cents, multiplier, status
`

type CreateModelParams struct {
	ModelName           string
	InputPriceCents     int64
	OutputPriceCents    int64
	CacheHitPriceCents  int64
	CacheMissPriceCents int64
	Multiplier          float32
	Status              pgtype.Int4
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, createModel,
		arg.ModelName,
		arg.InputPriceCents,
		arg.OutputPriceCents,
		arg.CacheHitPriceCents,
		arg.CacheMissPriceCents,
		arg.Multiplier,
		arg.Status,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.InputPriceCents,
		&i.OutputPriceCents,
		&i.CacheHitPriceCents,
		&i.CacheMissPriceCents,
		&i.Multiplier,
		&i.Status,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     int32
	UserID pgtype.Int4
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	return err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM models WHERE model_name = $1
`

func (q *Queries) DeleteModel(ctx context.Context, modelName string) error {
	_, err := q.db.Exec(ctx, deleteModel, modelName)
	return err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, provider, base_url, api_key, models, weight, status FROM channels WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChannelByID(ctx context.Context, id int32) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.Weight,
		&i.Status,
	)
	return i, err
}

const getModelByName = `-- name: GetModelByName :one
SELECT id, model_name, input_price_cents, output_price_cents, cache_hit_price_cents, cache_miss_price_cents, multiplier, status FROM models WHERE model_name = $1 AND status = 1 LIMIT 1
`

func (q *Queries) GetModelByName(ctx context.Context, modelName string) (Model, error) {
	row := q.db.QueryRow(ctx, getModelByName, modelName)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.InputPriceCents,
		&i.OutputPriceCents,
		&i.CacheHitPriceCents,
		&i.CacheMissPriceCents,
		&i.Multiplier,
		&i.Status,
	)
	return i, err
}

const getUserAPIKeys = `-- name: GetUserAPIKeys :many
SELECT
    id,
    name,
    key_string,
    order_id,
    product_id,
    tier_level,
    quota_limit,
    quota_used,
    allowed_models,
    status,
    created_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetUserAPIKeysRow struct {
	ID            int32
	Name          string
	KeyString     string
	OrderID       pgtype.Text
	ProductID     pgtype.Int4
	TierLevel     pgtype.Int4
	QuotaLimit    pgtype.Int8
	QuotaUsed     pgtype.Int8
	AllowedModels []byte
	Status        pgtype.Int4
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetUserAPIKeys(ctx context.Context, userID pgtype.Int4) ([]GetUserAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, getUserAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAPIKeysRow
	for rows.Next() {
		var i GetUserAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyString,
			&i.OrderID,
			&i.ProductID,
			&i.TierLevel,
			&i.QuotaLimit,
			&i.QuotaUsed,
			&i.AllowedModels,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBillingLogs = `-- name: GetUserBillingLogs :many
SELECT 
    id,
    created_at,
    model_name,
    prompt_tokens,
    completion_tokens,
    amount_cents
FROM billing_logs
WHERE user_id = $1
  AND ($2::varchar = '' OR model_name = $2)
  AND created_at >= $3
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type GetUserBillingLogsParams struct {
	UserID    pgtype.Int4
	ModelName string
	StartTime pgtype.Timestamptz
	OffsetVal int32
	LimitVal  int32
}

type GetUserBillingLogsRow struct {
	ID               pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	AmountCents      int64
}

func (q *Queries) GetUserBillingLogs(ctx context.Context, arg GetUserBillingLogsParams) ([]GetUserBillingLogsRow, error) {
	rows, err := q.db.Query(ctx, getUserBillingLogs,
		arg.UserID,
		arg.ModelName,
		arg.StartTime,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBillingLogsRow
	for rows.Next() {
		var i GetUserBillingLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ModelName,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.AmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT
    u.id,
    u.email,
    u.password_hash,
    u.nickname,
    u.avatar_url,
    u.cash_balance,
    u.grant_balance,
    u.tier_level AS user_tier,
    u.grant_expires_at,
    u.status,
    u.last_login_at,
    u.created_at,
    ak.id AS key_id,
    ak.name AS key_name,
    ak.key_string,
    ak.order_id,
    ak.product_id,
    ak.tier_level AS key_tier,
    ak.quota_limit,
    ak.quota_used,
    ak.allowed_models,
    ak.status AS key_status
FROM users u
    JOIN api_keys ak ON u.id = ak.user_id
WHERE
    ak.key_string = $1
    AND ak.status = 1
    AND u.status = 1
LIMIT 1
`

type GetUserByAPIKeyRow struct {
	ID             int32
	Email          string
	PasswordHash   string
	Nickname       pgtype.Text
	AvatarUrl      pgtype.Text
	CashBalance    pgtype.Int8
	GrantBalance   pgtype.Int8
	UserTier       pgtype.Int4
	GrantExpiresAt pgtype.Timestamptz
	Status         pgtype.Int4
	LastLoginAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	KeyID          int32
	KeyName        string
	KeyString      string
	OrderID        pgtype.Text
	ProductID      pgtype.Int4
	KeyTier        pgtype.Int4
	QuotaLimit     pgtype.Int8
	QuotaUsed      pgtype.Int8
	AllowedModels  []byte
	KeyStatus      pgtype.Int4
}

func (q *Queries) GetUserByAPIKey(ctx context.Context, keyString string) (GetUserByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, keyString)
	var i GetUserByAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.AvatarUrl,
		&i.CashBalance,
		&i.GrantBalance,
		&i.UserTier,
		&i.GrantExpiresAt,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.KeyID,
		&i.KeyName,
		&i.KeyString,
		&i.OrderID,
		&i.ProductID,
		&i.KeyTier,
		&i.QuotaLimit,
		&i.QuotaUsed,
		&i.AllowedModels,
		&i.KeyStatus,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, nickname, avatar_url, cash_balance, grant_balance, tier_level, grant_expires_at, status, last_login_at, created_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.AvatarUrl,
		&i.CashBalance,
		&i.GrantBalance,
		&i.TierLevel,
		&i.GrantExpiresAt,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserModelStats = `-- name: GetUserModelStats :many
SELECT 
    model_name,
    COUNT(*) as request_count,
    COALESCE(SUM(amount_cents), 0)::bigint as total_amount
FROM billing_logs
WHERE user_id = $1 AND created_at >= $2
GROUP BY model_name
ORDER BY total_amount DESC
`

type GetUserModelStatsParams struct {
	UserID    pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type GetUserModelStatsRow struct {
	ModelName    string
	RequestCount int64
	TotalAmount  int64
}

func (q *Queries) GetUserModelStats(ctx context.Context, arg GetUserModelStatsParams) ([]GetUserModelStatsRow, error) {
	rows, err := q.db.Query(ctx, getUserModelStats, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserModelStatsRow
	for rows.Next() {
		var i GetUserModelStatsRow
		if err := rows.Scan(&i.ModelName, &i.RequestCount, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStatsSummary = `-- name: GetUserStatsSummary :one

SELECT 
    COALESCE(SUM(amount_cents), 0)::bigint as total_amount,
    COALESCE(SUM(prompt_tokens), 0)::bigint as total_prompt_tokens,
    COALESCE(SUM(completion_tokens), 0)::bigint as total_completion_tokens,
    COALESCE(SUM(cache_hit_tokens), 0)::bigint as total_cache_hit_tokens,
    COALESCE(SUM(cache_miss_tokens), 0)::bigint as total_cache_miss_tokens
FROM billing_logs
WHERE user_id = $1 AND created_at >= $2
`

type GetUserStatsSummaryParams struct {
	UserID    pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type GetUserStatsSummaryRow struct {
	TotalAmount           int64
	TotalPromptTokens     int64
	TotalCompletionTokens int64
	TotalCacheHitTokens   int64
	TotalCacheMissTokens  int64
}

// ==========================================
// Internal API Queries (User Dashboard Stats)
// ==========================================
func (q *Queries) GetUserStatsSummary(ctx context.Context, arg GetUserStatsSummaryParams) (GetUserStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getUserStatsSummary, arg.UserID, arg.CreatedAt)
	var i GetUserStatsSummaryRow
	err := row.Scan(
		&i.TotalAmount,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.TotalCacheHitTokens,
		&i.TotalCacheMissTokens,
	)
	return i, err
}

const getUserTrendSeries = `-- name: GetUserTrendSeries :many
SELECT 
    DATE(created_at) as date,
    COUNT(*) as request_count,
    COALESCE(SUM(amount_cents), 0)::bigint as daily_amount
FROM billing_logs
WHERE user_id = $1 AND created_at >= $2
GROUP BY DATE(created_at)
ORDER BY date ASC
`

type GetUserTrendSeriesParams struct {
	UserID    pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type GetUserTrendSeriesRow struct {
	Date         pgtype.Date
	RequestCount int64
	DailyAmount  int64
}

func (q *Queries) GetUserTrendSeries(ctx context.Context, arg GetUserTrendSeriesParams) ([]GetUserTrendSeriesRow, error) {
	rows, err := q.db.Query(ctx, getUserTrendSeries, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTrendSeriesRow
	for rows.Next() {
		var i GetUserTrendSeriesRow
		if err := rows.Scan(&i.Date, &i.RequestCount, &i.DailyAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveChannels = `-- name: ListActiveChannels :many
SELECT id, name, provider, base_url, api_key, models, weight, status FROM channels WHERE status = 1 ORDER BY weight DESC
`

func (q *Queries) ListActiveChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listActiveChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Models,
			&i.Weight,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveModels = `-- name: ListActiveModels :many
SELECT id, model_name, input_price_cents, output_price_cents, cache_hit_price_cents, cache_miss_price_cents, multiplier, status FROM models WHERE status = 1 ORDER BY model_name ASC
`

func (q *Queries) ListActiveModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listActiveModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ModelName,
			&i.InputPriceCents,
			&i.OutputPriceCents,
			&i.CacheHitPriceCents,
			&i.CacheMissPriceCents,
			&i.Multiplier,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllChannels = `-- name: ListAllChannels :many
SELECT id, name, provider, base_url, api_key, models, weight, status FROM channels ORDER BY id DESC
`

func (q *Queries) ListAllChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listAllChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Models,
			&i.Weight,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllModelsForAdmin = `-- name: ListAllModelsForAdmin :many
SELECT id, model_name, input_price_cents, output_price_cents, cache_hit_price_cents, cache_miss_price_cents, multiplier, status FROM models ORDER BY model_name ASC
`

func (q *Queries) ListAllModelsForAdmin(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listAllModelsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ModelName,
			&i.InputPriceCents,
			&i.OutputPriceCents,
			&i.CacheHitPriceCents,
			&i.CacheMissPriceCents,
			&i.Multiplier,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingLogs = `-- name: ListBillingLogs :many
SELECT id, user_id, channel_id, model_name, prompt_tokens, completion_tokens, cache_hit_tokens, cache_miss_tokens, amount_cents, request_id, created_at
FROM billing_logs
ORDER BY created_at DESC
LIMIT $1
OFFSET
    $2
`

type ListBillingLogsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListBillingLogs(ctx context.Context, arg ListBillingLogsParams) ([]BillingLog, error) {
	rows, err := q.db.Query(ctx, listBillingLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingLog
	for rows.Next() {
		var i BillingLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelID,
			&i.ModelName,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CacheHitTokens,
			&i.CacheMissTokens,
			&i.AmountCents,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateAPIKey = `-- name: RotateAPIKey :exec
UPDATE api_keys SET key_string = $1 WHERE id = $2 AND user_id = $3
`

type RotateAPIKeyParams struct {
	KeyString string
	ID        int32
	UserID    pgtype.Int4
}

func (q *Queries) RotateAPIKey(ctx context.Context, arg RotateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, rotateAPIKey, arg.KeyString, arg.ID, arg.UserID)
	return err
}

const updateAPIKeyName = `-- name: UpdateAPIKeyName :exec
UPDATE api_keys SET name = $1 WHERE id = $2 AND user_id = $3
`

type UpdateAPIKeyNameParams struct {
	Name   string
	ID     int32
	UserID pgtype.Int4
}

func (q *Queries) UpdateAPIKeyName(ctx context.Context, arg UpdateAPIKeyNameParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyName, arg.Name, arg.ID, arg.UserID)
	return err
}

const updateAPIKeyStatus = `-- name: UpdateAPIKeyStatus :exec
UPDATE api_keys SET status = $1 WHERE id = $2 AND user_id = $3
`

type UpdateAPIKeyStatusParams struct {
	Status pgtype.Int4
	ID     int32
	UserID pgtype.Int4
}

func (q *Queries) UpdateAPIKeyStatus(ctx context.Context, arg UpdateAPIKeyStatusParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyStatus, arg.Status, arg.ID, arg.UserID)
	return err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET
    name = $2,
    provider = $3,
    base_url = $4,
    api_key = $5,
    weight = $6,
    models = $7,
    status = $8
WHERE
    id = $1 RETURNING id, name, provider, base_url, api_key, models, weight, status
`

type UpdateChannelParams struct {
	ID       int32
	Name     string
	Provider string
	BaseUrl  string
	ApiKey   string
	Weight   pgtype.Int4
	Models   string
	Status   pgtype.Int4
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Provider,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Weight,
		arg.Models,
		arg.Status,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.Weight,
		&i.Status,
	)
	return i, err
}

const updateChannelStatus = `-- name: UpdateChannelStatus :exec
UPDATE channels SET status = $2 WHERE id = $1
`

type UpdateChannelStatusParams struct {
	ID     int32
	Status pgtype.Int4
}

func (q *Queries) UpdateChannelStatus(ctx context.Context, arg UpdateChannelStatusParams) error {
	_, err := q.db.Exec(ctx, updateChannelStatus, arg.ID, arg.Status)
	return err
}

const updateModel = `-- name: UpdateModel :one
UPDATE models
SET
    input_price_cents = $2,
    output_price_cents = $3,
    cache_hit_price_cents = $4,
    cache_miss_price_cents = $5,
    multiplier = $6,
    status = $7
WHERE
    model_name = $1 RETURNING id, model_name, input_price_cents, output_price_cents, cache_hit_price_cents, cache_miss_price_cents, multiplier, status
`

type UpdateModelParams struct {
	ModelName           string
	InputPriceCents     int64
	OutputPriceCents    int64
	CacheHitPriceCents  int64
	CacheMissPriceCents int64
	Multiplier          float32
	Status              pgtype.Int4
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, updateModel,
		arg.ModelName,
		arg.InputPriceCents,
		arg.OutputPriceCents,
		arg.CacheHitPriceCents,
		arg.CacheMissPriceCents,
		arg.Multiplier,
		arg.Status,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.InputPriceCents,
		&i.OutputPriceCents,
		&i.CacheHitPriceCents,
		&i.CacheMissPriceCents,
		&i.Multiplier,
		&i.Status,
	)
	return i, err
}

const updateUserGrantBalance = `-- name: UpdateUserGrantBalance :exec
UPDATE users
SET
    grant_balance = grant_balance + $2
WHERE
    id = $1
`

type UpdateUserGrantBalanceParams struct {
	ID           int32
	GrantBalance pgtype.Int8
}

func (q *Queries) UpdateUserGrantBalance(ctx context.Context, arg UpdateUserGrantBalanceParams) error {
	_, err := q.db.Exec(ctx, updateUserGrantBalance, arg.ID, arg.GrantBalance)
	return err
}

const updateUserSubBalance = `-- name: UpdateUserSubBalance :exec
UPDATE users
SET
    grant_balance = $2,
    grant_expires_at = $3,
    tier_level = $4
WHERE
    id = $1
`

type UpdateUserSubBalanceParams struct {
	ID             int32
	GrantBalance   pgtype.Int8
	GrantExpiresAt pgtype.Timestamptz
	TierLevel      pgtype.Int4
}

func (q *Queries) UpdateUserSubBalance(ctx context.Context, arg UpdateUserSubBalanceParams) error {
	_, err := q.db.Exec(ctx, updateUserSubBalance,
		arg.ID,
		arg.GrantBalance,
		arg.GrantExpiresAt,
		arg.TierLevel,
	)
	return err
}

const updateUserTopupBalance = `-- name: UpdateUserTopupBalance :exec
UPDATE users
SET
    cash_balance = cash_balance + $2
WHERE
    id = $1
`

type UpdateUserTopupBalanceParams struct {
	ID          int32
	CashBalance pgtype.Int8
}

func (q *Queries) UpdateUserTopupBalance(ctx context.Context, arg UpdateUserTopupBalanceParams) error {
	_, err := q.db.Exec(ctx, updateUserTopupBalance, arg.ID, arg.CashBalance)
	return err
}
