// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkBillingLogExists = `-- name: CheckBillingLogExists :one
SELECT EXISTS (
        SELECT 1
        FROM billing_logs
        WHERE
            request_id = $1
    )
`

func (q *Queries) CheckBillingLogExists(ctx context.Context, requestID pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkBillingLogExists, requestID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countActiveUserAPIKeys = `-- name: CountActiveUserAPIKeys :one
SELECT COUNT(*) FROM api_keys WHERE user_id = $1 AND status = 1
`

func (q *Queries) CountActiveUserAPIKeys(ctx context.Context, userID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUserAPIKeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBalanceLogsByUser = `-- name: CountBalanceLogsByUser :one
SELECT COUNT(*)
FROM balance_logs
WHERE user_id = $1
`

func (q *Queries) CountBalanceLogsByUser(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countBalanceLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBillingLogs = `-- name: CountBillingLogs :one
SELECT COUNT(*) FROM billing_logs
`

func (q *Queries) CountBillingLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBillingLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChannelFailureLogsByChannel = `-- name: CountChannelFailureLogsByChannel :one
SELECT COUNT(*)
FROM channel_failure_logs
WHERE channel_id = $1
`

func (q *Queries) CountChannelFailureLogsByChannel(ctx context.Context, channelID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelFailureLogsByChannel, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserBillingLogs = `-- name: CountUserBillingLogs :one
SELECT COUNT(*)
FROM billing_logs
WHERE user_id = $1
  AND ($2::varchar = '' OR model_name = $2)
  AND created_at >= $3
`

type CountUserBillingLogsParams struct {
	UserID    pgtype.Int4
	ModelName string
	StartTime pgtype.Timestamptz
}

func (q *Queries) CountUserBillingLogs(ctx context.Context, arg CountUserBillingLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserBillingLogs, arg.UserID, arg.ModelName, arg.StartTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserModelFailureLogs = `-- name: CountUserModelFailureLogs :one
SELECT COUNT(*)
FROM model_failure_logs
WHERE user_id = $1
  AND ($2::varchar = '' OR model_name = $2)
  AND created_at >= $3
`

type CountUserModelFailureLogsParams struct {
	UserID    int32
	ModelName string
	StartTime pgtype.Timestamptz
}

func (q *Queries) CountUserModelFailureLogs(ctx context.Context, arg CountUserModelFailureLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserModelFailureLogs, arg.UserID, arg.ModelName, arg.StartTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersForAdmin = `-- name: CountUsersForAdmin :one
SELECT COUNT(*)
FROM users u
WHERE
    (
        $1::text = ''
        OR u.email ILIKE '%' || $1::text || '%'
        OR COALESCE(u.nickname, '') ILIKE '%' || $1::text || '%'
    )
`

func (q *Queries) CountUsersForAdmin(ctx context.Context, keyword string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersForAdmin, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    name,
    key_string,
    user_id,
    allowed_models,
    status,
    tier_level
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, key_string, allowed_models, status, created_at
`

type CreateAPIKeyParams struct {
	Name          string
	KeyString     string
	UserID        pgtype.Int4
	AllowedModels []byte
	Status        pgtype.Int4
	TierLevel     pgtype.Int4
}

type CreateAPIKeyRow struct {
	ID            int32
	Name          string
	KeyString     string
	AllowedModels []byte
	Status        pgtype.Int4
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.KeyString,
		arg.UserID,
		arg.AllowedModels,
		arg.Status,
		arg.TierLevel,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyString,
		&i.AllowedModels,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createAsyncTask = `-- name: CreateAsyncTask :one

INSERT INTO
    async_tasks (
        id,
        user_id,
        channel_id,
        request_id,
        task_type,
        provider,
        model_name,
        status,
        upstream_task_id,
        input_payload,
        output_payload,
        error_payload,
        metadata,
        pre_deducted_cents,
        grant_deducted,
        cash_deducted,
        actual_cost_cents
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17
    ) RETURNING id, user_id, channel_id, request_id, task_type, provider, model_name, status, upstream_task_id, input_payload, output_payload, error_payload, metadata, pre_deducted_cents, grant_deducted, cash_deducted, actual_cost_cents, created_at, updated_at, submitted_at, finished_at, canceled_at, sub_deducted
`

type CreateAsyncTaskParams struct {
	ID               string
	UserID           int32
	ChannelID        pgtype.Int4
	RequestID        string
	TaskType         string
	Provider         string
	ModelName        string
	Status           string
	UpstreamTaskID   pgtype.Text
	InputPayload     []byte
	OutputPayload    []byte
	ErrorPayload     []byte
	Metadata         []byte
	PreDeductedCents int64
	GrantDeducted    int64
	CashDeducted     int64
	ActualCostCents  int64
}

// ==========================================
// Async Task Queries
// ==========================================
func (q *Queries) CreateAsyncTask(ctx context.Context, arg CreateAsyncTaskParams) (AsyncTask, error) {
	row := q.db.QueryRow(ctx, createAsyncTask,
		arg.ID,
		arg.UserID,
		arg.ChannelID,
		arg.RequestID,
		arg.TaskType,
		arg.Provider,
		arg.ModelName,
		arg.Status,
		arg.UpstreamTaskID,
		arg.InputPayload,
		arg.OutputPayload,
		arg.ErrorPayload,
		arg.Metadata,
		arg.PreDeductedCents,
		arg.GrantDeducted,
		arg.CashDeducted,
		arg.ActualCostCents,
	)
	var i AsyncTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.RequestID,
		&i.TaskType,
		&i.Provider,
		&i.ModelName,
		&i.Status,
		&i.UpstreamTaskID,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ErrorPayload,
		&i.Metadata,
		&i.PreDeductedCents,
		&i.GrantDeducted,
		&i.CashDeducted,
		&i.ActualCostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.FinishedAt,
		&i.CanceledAt,
		&i.SubDeducted,
	)
	return i, err
}

const createBalanceLog = `-- name: CreateBalanceLog :exec
INSERT INTO balance_logs (
    transaction_id,
    user_id,
    balance_type,
    action_type,
    amount_cents,
    before_balance_cents,
    after_balance_cents,
    operator_admin_id,
    operator_name,
    remark
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateBalanceLogParams struct {
	TransactionID      pgtype.Int8
	UserID             int32
	BalanceType        string
	ActionType         string
	AmountCents        int64
	BeforeBalanceCents int64
	AfterBalanceCents  int64
	OperatorAdminID    pgtype.Int4
	OperatorName       string
	Remark             string
}

func (q *Queries) CreateBalanceLog(ctx context.Context, arg CreateBalanceLogParams) error {
	_, err := q.db.Exec(ctx, createBalanceLog,
		arg.TransactionID,
		arg.UserID,
		arg.BalanceType,
		arg.ActionType,
		arg.AmountCents,
		arg.BeforeBalanceCents,
		arg.AfterBalanceCents,
		arg.OperatorAdminID,
		arg.OperatorName,
		arg.Remark,
	)
	return err
}

const createBillingLog = `-- name: CreateBillingLog :one
INSERT INTO
    billing_logs (
        id,
        user_id,
        channel_id,
        model_name,
        prompt_tokens,
        completion_tokens,
        cache_hit_tokens,
        cache_miss_tokens,
        amount_cents,
        log_type,
        pre_deducted_cents,
        request_id
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    ) RETURNING id, user_id, channel_id, model_name, prompt_tokens, completion_tokens, cache_hit_tokens, cache_miss_tokens, amount_cents, log_type, pre_deducted_cents, request_id, created_at
`

type CreateBillingLogParams struct {
	ID               pgtype.UUID
	UserID           pgtype.Int4
	ChannelID        pgtype.Int4
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	LogType          string
	PreDeductedCents int64
	RequestID        pgtype.Text
}

func (q *Queries) CreateBillingLog(ctx context.Context, arg CreateBillingLogParams) (BillingLog, error) {
	row := q.db.QueryRow(ctx, createBillingLog,
		arg.ID,
		arg.UserID,
		arg.ChannelID,
		arg.ModelName,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CacheHitTokens,
		arg.CacheMissTokens,
		arg.AmountCents,
		arg.LogType,
		arg.PreDeductedCents,
		arg.RequestID,
	)
	var i BillingLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.ModelName,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CacheHitTokens,
		&i.CacheMissTokens,
		&i.AmountCents,
		&i.LogType,
		&i.PreDeductedCents,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const createChannel = `-- name: CreateChannel :one

INSERT INTO
    channels (
        name,
        provider,
        base_url,
        api_key,
        weight,
        models,
        protocol_type,
        upload_mode,
        model_mapping,
        supports_async,
        status
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, name, provider, base_url, api_key, models, protocol_type, upload_mode, model_mapping, supports_async, weight, status
`

type CreateChannelParams struct {
	Name          string
	Provider      string
	BaseUrl       string
	ApiKey        string
	Weight        pgtype.Int4
	Models        string
	ProtocolType  string
	UploadMode    string
	ModelMapping  []byte
	SupportsAsync bool
	Status        pgtype.Int4
}

// ==========================================
// Admin API Queries (Admin Panel CRUD)
// ==========================================
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.Provider,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Weight,
		arg.Models,
		arg.ProtocolType,
		arg.UploadMode,
		arg.ModelMapping,
		arg.SupportsAsync,
		arg.Status,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ProtocolType,
		&i.UploadMode,
		&i.ModelMapping,
		&i.SupportsAsync,
		&i.Weight,
		&i.Status,
	)
	return i, err
}

const createChannelFailureLog = `-- name: CreateChannelFailureLog :exec
INSERT INTO channel_failure_logs (
    channel_id,
    request_id,
    model_name,
    provider,
    upstream_base_url,
    error_type,
    status_code,
    response_body,
    error_message,
    latency_ms,
    circuit_state
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateChannelFailureLogParams struct {
	ChannelID       int32
	RequestID       string
	ModelName       string
	Provider        string
	UpstreamBaseUrl string
	ErrorType       string
	StatusCode      int32
	ResponseBody    string
	ErrorMessage    string
	LatencyMs       int32
	CircuitState    string
}

func (q *Queries) CreateChannelFailureLog(ctx context.Context, arg CreateChannelFailureLogParams) error {
	_, err := q.db.Exec(ctx, createChannelFailureLog,
		arg.ChannelID,
		arg.RequestID,
		arg.ModelName,
		arg.Provider,
		arg.UpstreamBaseUrl,
		arg.ErrorType,
		arg.StatusCode,
		arg.ResponseBody,
		arg.ErrorMessage,
		arg.LatencyMs,
		arg.CircuitState,
	)
	return err
}

const createModel = `-- name: CreateModel :one
INSERT INTO
    models (
        model_name,
        input_price_cents,
        output_price_cents,
        cache_hit_price_cents,
        cache_miss_price_cents,
        multiplier,
        billing_policy,
        modality,
        pricing_mode,
        pricing_config,
        max_concurrency,
        status
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING
    id,
    model_name,
    input_price_cents,
    output_price_cents,
    cache_hit_price_cents,
    cache_miss_price_cents,
    multiplier,
    billing_policy,
    modality,
    pricing_mode,
    pricing_config,
    max_concurrency,
    status
`

type CreateModelParams struct {
	ModelName           string
	InputPriceCents     int64
	OutputPriceCents    int64
	CacheHitPriceCents  int64
	CacheMissPriceCents int64
	Multiplier          float32
	BillingPolicy       string
	Modality            string
	PricingMode         string
	PricingConfig       []byte
	MaxConcurrency      int32
	Status              pgtype.Int4
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, createModel,
		arg.ModelName,
		arg.InputPriceCents,
		arg.OutputPriceCents,
		arg.CacheHitPriceCents,
		arg.CacheMissPriceCents,
		arg.Multiplier,
		arg.BillingPolicy,
		arg.Modality,
		arg.PricingMode,
		arg.PricingConfig,
		arg.MaxConcurrency,
		arg.Status,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.InputPriceCents,
		&i.OutputPriceCents,
		&i.CacheHitPriceCents,
		&i.CacheMissPriceCents,
		&i.Multiplier,
		&i.BillingPolicy,
		&i.Modality,
		&i.PricingMode,
		&i.PricingConfig,
		&i.MaxConcurrency,
		&i.Status,
	)
	return i, err
}

const createModelFailureLog = `-- name: CreateModelFailureLog :exec
INSERT INTO model_failure_logs (
    user_id,
    api_key_id,
    request_id,
    model_name,
    provider,
    error_type,
    error_code,
    status_code,
    error_message,
    response_body,
    latency_ms,
    is_retryable
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
`

type CreateModelFailureLogParams struct {
	UserID       int32
	ApiKeyID     pgtype.Int4
	RequestID    string
	ModelName    string
	Provider     string
	ErrorType    string
	ErrorCode    string
	StatusCode   int32
	ErrorMessage string
	ResponseBody string
	LatencyMs    int32
	IsRetryable  bool
}

func (q *Queries) CreateModelFailureLog(ctx context.Context, arg CreateModelFailureLogParams) error {
	_, err := q.db.Exec(ctx, createModelFailureLog,
		arg.UserID,
		arg.ApiKeyID,
		arg.RequestID,
		arg.ModelName,
		arg.Provider,
		arg.ErrorType,
		arg.ErrorCode,
		arg.StatusCode,
		arg.ErrorMessage,
		arg.ResponseBody,
		arg.LatencyMs,
		arg.IsRetryable,
	)
	return err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    event_id,
    type,
    balance_type,
    direction,
    amount_cents,
    before_balance_cents,
    after_balance_cents,
    source_type,
    source_id,
    status,
    remark,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING
    id,
    user_id,
    event_id,
    type,
    balance_type,
    direction,
    amount_cents,
    before_balance_cents,
    after_balance_cents,
    source_type,
    source_id,
    status,
    remark,
    metadata,
    created_at
`

type CreateTransactionParams struct {
	UserID             int32
	EventID            pgtype.Text
	Type               string
	BalanceType        string
	Direction          string
	AmountCents        int64
	BeforeBalanceCents int64
	AfterBalanceCents  int64
	SourceType         string
	SourceID           string
	Status             string
	Remark             string
	Metadata           []byte
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.EventID,
		arg.Type,
		arg.BalanceType,
		arg.Direction,
		arg.AmountCents,
		arg.BeforeBalanceCents,
		arg.AfterBalanceCents,
		arg.SourceType,
		arg.SourceID,
		arg.Status,
		arg.Remark,
		arg.Metadata,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Type,
		&i.BalanceType,
		&i.Direction,
		&i.AmountCents,
		&i.BeforeBalanceCents,
		&i.AfterBalanceCents,
		&i.SourceType,
		&i.SourceID,
		&i.Status,
		&i.Remark,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     int32
	UserID pgtype.Int4
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	return err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM models WHERE model_name = $1
`

func (q *Queries) DeleteModel(ctx context.Context, modelName string) error {
	_, err := q.db.Exec(ctx, deleteModel, modelName)
	return err
}

const getAsyncTaskByIDAndUser = `-- name: GetAsyncTaskByIDAndUser :one
SELECT id, user_id, channel_id, request_id, task_type, provider, model_name, status, upstream_task_id, input_payload, output_payload, error_payload, metadata, pre_deducted_cents, grant_deducted, cash_deducted, actual_cost_cents, created_at, updated_at, submitted_at, finished_at, canceled_at, sub_deducted
FROM async_tasks
WHERE
    id = $1
    AND user_id = $2
LIMIT 1
`

type GetAsyncTaskByIDAndUserParams struct {
	ID     string
	UserID int32
}

func (q *Queries) GetAsyncTaskByIDAndUser(ctx context.Context, arg GetAsyncTaskByIDAndUserParams) (AsyncTask, error) {
	row := q.db.QueryRow(ctx, getAsyncTaskByIDAndUser, arg.ID, arg.UserID)
	var i AsyncTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.RequestID,
		&i.TaskType,
		&i.Provider,
		&i.ModelName,
		&i.Status,
		&i.UpstreamTaskID,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ErrorPayload,
		&i.Metadata,
		&i.PreDeductedCents,
		&i.GrantDeducted,
		&i.CashDeducted,
		&i.ActualCostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.FinishedAt,
		&i.CanceledAt,
		&i.SubDeducted,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, provider, base_url, api_key, models, protocol_type, upload_mode, model_mapping, supports_async, weight, status FROM channels WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChannelByID(ctx context.Context, id int32) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ProtocolType,
		&i.UploadMode,
		&i.ModelMapping,
		&i.SupportsAsync,
		&i.Weight,
		&i.Status,
	)
	return i, err
}

const getModelByName = `-- name: GetModelByName :one
SELECT
    id,
    model_name,
    input_price_cents,
    output_price_cents,
    cache_hit_price_cents,
    cache_miss_price_cents,
    multiplier,
    billing_policy,
    modality,
    pricing_mode,
    pricing_config,
    max_concurrency,
    status
FROM models
WHERE
    model_name = $1
    AND status = 1
LIMIT 1
`

func (q *Queries) GetModelByName(ctx context.Context, modelName string) (Model, error) {
	row := q.db.QueryRow(ctx, getModelByName, modelName)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.InputPriceCents,
		&i.OutputPriceCents,
		&i.CacheHitPriceCents,
		&i.CacheMissPriceCents,
		&i.Multiplier,
		&i.BillingPolicy,
		&i.Modality,
		&i.PricingMode,
		&i.PricingConfig,
		&i.MaxConcurrency,
		&i.Status,
	)
	return i, err
}

const getTransactionByEventID = `-- name: GetTransactionByEventID :one
SELECT id, user_id, event_id, type, balance_type, direction, amount_cents, before_balance_cents, after_balance_cents, source_type, source_id, status, remark, metadata, created_at
FROM transactions
WHERE event_id = $1
LIMIT 1
`

func (q *Queries) GetTransactionByEventID(ctx context.Context, eventID pgtype.Text) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByEventID, eventID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Type,
		&i.BalanceType,
		&i.Direction,
		&i.AmountCents,
		&i.BeforeBalanceCents,
		&i.AfterBalanceCents,
		&i.SourceType,
		&i.SourceID,
		&i.Status,
		&i.Remark,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAPIKeys = `-- name: GetUserAPIKeys :many
SELECT
    id,
    name,
    key_string,
    order_id,
    product_id,
    tier_level,
    quota_limit,
    quota_used,
    allowed_models,
    status,
    created_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetUserAPIKeysRow struct {
	ID            int32
	Name          string
	KeyString     string
	OrderID       pgtype.Text
	ProductID     pgtype.Int4
	TierLevel     pgtype.Int4
	QuotaLimit    pgtype.Int8
	QuotaUsed     pgtype.Int8
	AllowedModels []byte
	Status        pgtype.Int4
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetUserAPIKeys(ctx context.Context, userID pgtype.Int4) ([]GetUserAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, getUserAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAPIKeysRow
	for rows.Next() {
		var i GetUserAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyString,
			&i.OrderID,
			&i.ProductID,
			&i.TierLevel,
			&i.QuotaLimit,
			&i.QuotaUsed,
			&i.AllowedModels,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBillingLogs = `-- name: GetUserBillingLogs :many
SELECT 
    id,
    created_at,
    model_name,
    prompt_tokens,
    completion_tokens,
    cache_hit_tokens,
    cache_miss_tokens,
    amount_cents,
    log_type,
    pre_deducted_cents
FROM billing_logs
WHERE user_id = $1
  AND ($2::varchar = '' OR model_name = $2)
  AND created_at >= $3
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type GetUserBillingLogsParams struct {
	UserID    pgtype.Int4
	ModelName string
	StartTime pgtype.Timestamptz
	OffsetVal int32
	LimitVal  int32
}

type GetUserBillingLogsRow struct {
	ID               pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	ModelName        string
	PromptTokens     pgtype.Int4
	CompletionTokens pgtype.Int4
	CacheHitTokens   pgtype.Int4
	CacheMissTokens  pgtype.Int4
	AmountCents      int64
	LogType          string
	PreDeductedCents int64
}

func (q *Queries) GetUserBillingLogs(ctx context.Context, arg GetUserBillingLogsParams) ([]GetUserBillingLogsRow, error) {
	rows, err := q.db.Query(ctx, getUserBillingLogs,
		arg.UserID,
		arg.ModelName,
		arg.StartTime,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBillingLogsRow
	for rows.Next() {
		var i GetUserBillingLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ModelName,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CacheHitTokens,
			&i.CacheMissTokens,
			&i.AmountCents,
			&i.LogType,
			&i.PreDeductedCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT
    u.id,
    u.email,
    u.password_hash,
    u.nickname,
    u.avatar_url,
    u.cash_balance,
    u.grant_balance,
    u.sub_balance,
    u.tier_level AS user_tier,
    u.sub_expires_at,
    u.status,
    u.last_login_at,
    u.created_at,
    ak.id AS key_id,
    ak.name AS key_name,
    ak.key_string,
    ak.order_id,
    ak.product_id,
    ak.tier_level AS key_tier,
    ak.quota_limit,
    ak.quota_used,
    ak.allowed_models,
    ak.status AS key_status
FROM users u
    JOIN api_keys ak ON u.id = ak.user_id
WHERE
    ak.key_string = $1
    AND ak.status = 1
    AND u.status = 1
LIMIT 1
`

type GetUserByAPIKeyRow struct {
	ID            int32
	Email         string
	PasswordHash  string
	Nickname      pgtype.Text
	AvatarUrl     pgtype.Text
	CashBalance   pgtype.Int8
	GrantBalance  pgtype.Int8
	SubBalance    int64
	UserTier      pgtype.Int4
	SubExpiresAt  pgtype.Timestamptz
	Status        pgtype.Int4
	LastLoginAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	KeyID         int32
	KeyName       string
	KeyString     string
	OrderID       pgtype.Text
	ProductID     pgtype.Int4
	KeyTier       pgtype.Int4
	QuotaLimit    pgtype.Int8
	QuotaUsed     pgtype.Int8
	AllowedModels []byte
	KeyStatus     pgtype.Int4
}

func (q *Queries) GetUserByAPIKey(ctx context.Context, keyString string) (GetUserByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, keyString)
	var i GetUserByAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.AvatarUrl,
		&i.CashBalance,
		&i.GrantBalance,
		&i.SubBalance,
		&i.UserTier,
		&i.SubExpiresAt,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.KeyID,
		&i.KeyName,
		&i.KeyString,
		&i.OrderID,
		&i.ProductID,
		&i.KeyTier,
		&i.QuotaLimit,
		&i.QuotaUsed,
		&i.AllowedModels,
		&i.KeyStatus,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, nickname, avatar_url, cash_balance, grant_balance, tier_level, status, last_login_at, created_at, sub_balance, sub_expires_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.AvatarUrl,
		&i.CashBalance,
		&i.GrantBalance,
		&i.TierLevel,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.SubBalance,
		&i.SubExpiresAt,
	)
	return i, err
}

const getUserByIDForUpdate = `-- name: GetUserByIDForUpdate :one
SELECT id, email, password_hash, nickname, avatar_url, cash_balance, grant_balance, tier_level, status, last_login_at, created_at, sub_balance, sub_expires_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUserByIDForUpdate(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.AvatarUrl,
		&i.CashBalance,
		&i.GrantBalance,
		&i.TierLevel,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.SubBalance,
		&i.SubExpiresAt,
	)
	return i, err
}

const getUserModelFailureLogs = `-- name: GetUserModelFailureLogs :many
SELECT
    id,
    user_id,
    api_key_id,
    request_id,
    model_name,
    provider,
    error_type,
    error_code,
    status_code,
    error_message,
    response_body,
    latency_ms,
    is_retryable,
    created_at
FROM model_failure_logs
WHERE user_id = $1
  AND ($2::varchar = '' OR model_name = $2)
  AND created_at >= $3
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type GetUserModelFailureLogsParams struct {
	UserID    int32
	ModelName string
	StartTime pgtype.Timestamptz
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) GetUserModelFailureLogs(ctx context.Context, arg GetUserModelFailureLogsParams) ([]ModelFailureLog, error) {
	rows, err := q.db.Query(ctx, getUserModelFailureLogs,
		arg.UserID,
		arg.ModelName,
		arg.StartTime,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelFailureLog
	for rows.Next() {
		var i ModelFailureLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.RequestID,
			&i.ModelName,
			&i.Provider,
			&i.ErrorType,
			&i.ErrorCode,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.ResponseBody,
			&i.LatencyMs,
			&i.IsRetryable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserModelStats = `-- name: GetUserModelStats :many
SELECT 
    model_name,
    COUNT(*) as request_count,
    COALESCE(SUM(amount_cents), 0)::bigint as total_amount
FROM billing_logs
WHERE user_id = $1 AND created_at >= $2
GROUP BY model_name
ORDER BY total_amount DESC
`

type GetUserModelStatsParams struct {
	UserID    pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type GetUserModelStatsRow struct {
	ModelName    string
	RequestCount int64
	TotalAmount  int64
}

func (q *Queries) GetUserModelStats(ctx context.Context, arg GetUserModelStatsParams) ([]GetUserModelStatsRow, error) {
	rows, err := q.db.Query(ctx, getUserModelStats, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserModelStatsRow
	for rows.Next() {
		var i GetUserModelStatsRow
		if err := rows.Scan(&i.ModelName, &i.RequestCount, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStatsSummary = `-- name: GetUserStatsSummary :one

SELECT 
    COALESCE(SUM(amount_cents), 0)::bigint as total_amount,
    COALESCE(SUM(prompt_tokens), 0)::bigint as total_prompt_tokens,
    COALESCE(SUM(completion_tokens), 0)::bigint as total_completion_tokens,
    COALESCE(SUM(cache_hit_tokens), 0)::bigint as total_cache_hit_tokens,
    COALESCE(SUM(cache_miss_tokens), 0)::bigint as total_cache_miss_tokens
FROM billing_logs
WHERE user_id = $1 AND created_at >= $2
`

type GetUserStatsSummaryParams struct {
	UserID    pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type GetUserStatsSummaryRow struct {
	TotalAmount           int64
	TotalPromptTokens     int64
	TotalCompletionTokens int64
	TotalCacheHitTokens   int64
	TotalCacheMissTokens  int64
}

// ==========================================
// Internal API Queries (User Dashboard Stats)
// ==========================================
func (q *Queries) GetUserStatsSummary(ctx context.Context, arg GetUserStatsSummaryParams) (GetUserStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getUserStatsSummary, arg.UserID, arg.CreatedAt)
	var i GetUserStatsSummaryRow
	err := row.Scan(
		&i.TotalAmount,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.TotalCacheHitTokens,
		&i.TotalCacheMissTokens,
	)
	return i, err
}

const getUserTrendSeries = `-- name: GetUserTrendSeries :many
SELECT 
    DATE(created_at) as date,
    COUNT(*) as request_count,
    COALESCE(SUM(amount_cents), 0)::bigint as daily_amount
FROM billing_logs
WHERE user_id = $1 AND created_at >= $2
GROUP BY DATE(created_at)
ORDER BY date ASC
`

type GetUserTrendSeriesParams struct {
	UserID    pgtype.Int4
	CreatedAt pgtype.Timestamptz
}

type GetUserTrendSeriesRow struct {
	Date         pgtype.Date
	RequestCount int64
	DailyAmount  int64
}

func (q *Queries) GetUserTrendSeries(ctx context.Context, arg GetUserTrendSeriesParams) ([]GetUserTrendSeriesRow, error) {
	rows, err := q.db.Query(ctx, getUserTrendSeries, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTrendSeriesRow
	for rows.Next() {
		var i GetUserTrendSeriesRow
		if err := rows.Scan(&i.Date, &i.RequestCount, &i.DailyAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersSummaryForAdmin = `-- name: GetUsersSummaryForAdmin :one
WITH filtered_users AS (
    SELECT
        id,
        cash_balance,
        grant_balance,
        status
    FROM users u
    WHERE
        (
            $1::text = ''
            OR u.email ILIKE '%' || $1::text || '%'
            OR COALESCE(u.nickname, '') ILIKE '%' || $1::text || '%'
        )
),
user_usage AS (
    SELECT
        user_id,
        COUNT(*)::bigint AS total_requests,
        (
            COALESCE(SUM(prompt_tokens), 0)::bigint +
            COALESCE(SUM(completion_tokens), 0)::bigint
        ) AS total_tokens
    FROM billing_logs
    WHERE user_id IN (SELECT id FROM filtered_users)
    GROUP BY user_id
),
active_keys AS (
    SELECT
        user_id,
        COUNT(*) FILTER (WHERE status = 1)::bigint AS active_key_count
    FROM api_keys
    WHERE user_id IN (SELECT id FROM filtered_users)
    GROUP BY user_id
)
SELECT
    COUNT(*)::bigint AS total_users,
    COUNT(*) FILTER (WHERE COALESCE(filtered_users.status, 0) = 1)::bigint AS active_users,
    COALESCE(SUM(filtered_users.cash_balance), 0)::bigint AS total_cash_balance,
    COALESCE(SUM(filtered_users.grant_balance), 0)::bigint AS total_grant_balance,
    COALESCE(SUM(COALESCE(user_usage.total_requests, 0)), 0)::bigint AS total_requests,
    COALESCE(SUM(COALESCE(user_usage.total_tokens, 0)), 0)::bigint AS total_tokens,
    COALESCE(SUM(COALESCE(active_keys.active_key_count, 0)), 0)::bigint AS total_active_keys
FROM filtered_users
LEFT JOIN user_usage ON user_usage.user_id = filtered_users.id
LEFT JOIN active_keys ON active_keys.user_id = filtered_users.id
`

type GetUsersSummaryForAdminRow struct {
	TotalUsers        int64
	ActiveUsers       int64
	TotalCashBalance  int64
	TotalGrantBalance int64
	TotalRequests     int64
	TotalTokens       int64
	TotalActiveKeys   int64
}

func (q *Queries) GetUsersSummaryForAdmin(ctx context.Context, keyword string) (GetUsersSummaryForAdminRow, error) {
	row := q.db.QueryRow(ctx, getUsersSummaryForAdmin, keyword)
	var i GetUsersSummaryForAdminRow
	err := row.Scan(
		&i.TotalUsers,
		&i.ActiveUsers,
		&i.TotalCashBalance,
		&i.TotalGrantBalance,
		&i.TotalRequests,
		&i.TotalTokens,
		&i.TotalActiveKeys,
	)
	return i, err
}

const incrementAPIKeyQuotaUsed = `-- name: IncrementAPIKeyQuotaUsed :exec
UPDATE api_keys SET quota_used = quota_used + $2 WHERE id = $1
`

type IncrementAPIKeyQuotaUsedParams struct {
	ID        int32
	QuotaUsed pgtype.Int8
}

func (q *Queries) IncrementAPIKeyQuotaUsed(ctx context.Context, arg IncrementAPIKeyQuotaUsedParams) error {
	_, err := q.db.Exec(ctx, incrementAPIKeyQuotaUsed, arg.ID, arg.QuotaUsed)
	return err
}

const listActiveChannels = `-- name: ListActiveChannels :many
SELECT id, name, provider, base_url, api_key, models, protocol_type, upload_mode, model_mapping, supports_async, weight, status FROM channels WHERE status = 1 ORDER BY weight DESC
`

func (q *Queries) ListActiveChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listActiveChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Models,
			&i.ProtocolType,
			&i.UploadMode,
			&i.ModelMapping,
			&i.SupportsAsync,
			&i.Weight,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveModels = `-- name: ListActiveModels :many
SELECT
    id,
    model_name,
    input_price_cents,
    output_price_cents,
    cache_hit_price_cents,
    cache_miss_price_cents,
    multiplier,
    billing_policy,
    modality,
    pricing_mode,
    pricing_config,
    max_concurrency,
    status
FROM models
WHERE
    status = 1
ORDER BY model_name ASC
`

func (q *Queries) ListActiveModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listActiveModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ModelName,
			&i.InputPriceCents,
			&i.OutputPriceCents,
			&i.CacheHitPriceCents,
			&i.CacheMissPriceCents,
			&i.Multiplier,
			&i.BillingPolicy,
			&i.Modality,
			&i.PricingMode,
			&i.PricingConfig,
			&i.MaxConcurrency,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllChannels = `-- name: ListAllChannels :many
SELECT id, name, provider, base_url, api_key, models, protocol_type, upload_mode, model_mapping, supports_async, weight, status FROM channels ORDER BY id DESC
`

func (q *Queries) ListAllChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listAllChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Models,
			&i.ProtocolType,
			&i.UploadMode,
			&i.ModelMapping,
			&i.SupportsAsync,
			&i.Weight,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllModelsForAdmin = `-- name: ListAllModelsForAdmin :many
SELECT
    id,
    model_name,
    input_price_cents,
    output_price_cents,
    cache_hit_price_cents,
    cache_miss_price_cents,
    multiplier,
    billing_policy,
    modality,
    pricing_mode,
    pricing_config,
    max_concurrency,
    status
FROM models
ORDER BY model_name ASC
`

func (q *Queries) ListAllModelsForAdmin(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listAllModelsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ModelName,
			&i.InputPriceCents,
			&i.OutputPriceCents,
			&i.CacheHitPriceCents,
			&i.CacheMissPriceCents,
			&i.Multiplier,
			&i.BillingPolicy,
			&i.Modality,
			&i.PricingMode,
			&i.PricingConfig,
			&i.MaxConcurrency,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalanceLogsByUser = `-- name: ListBalanceLogsByUser :many
SELECT
    id,
    transaction_id,
    user_id,
    balance_type,
    action_type,
    amount_cents,
    before_balance_cents,
    after_balance_cents,
    operator_admin_id,
    operator_name,
    remark,
    created_at
FROM balance_logs
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListBalanceLogsByUserParams struct {
	UserID    int32
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) ListBalanceLogsByUser(ctx context.Context, arg ListBalanceLogsByUserParams) ([]BalanceLog, error) {
	rows, err := q.db.Query(ctx, listBalanceLogsByUser, arg.UserID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceLog
	for rows.Next() {
		var i BalanceLog
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.UserID,
			&i.BalanceType,
			&i.ActionType,
			&i.AmountCents,
			&i.BeforeBalanceCents,
			&i.AfterBalanceCents,
			&i.OperatorAdminID,
			&i.OperatorName,
			&i.Remark,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingLogs = `-- name: ListBillingLogs :many
SELECT id, user_id, channel_id, model_name, prompt_tokens, completion_tokens, cache_hit_tokens, cache_miss_tokens, amount_cents, log_type, pre_deducted_cents, request_id, created_at
FROM billing_logs
ORDER BY created_at DESC
LIMIT $1
OFFSET
    $2
`

type ListBillingLogsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListBillingLogs(ctx context.Context, arg ListBillingLogsParams) ([]BillingLog, error) {
	rows, err := q.db.Query(ctx, listBillingLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingLog
	for rows.Next() {
		var i BillingLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelID,
			&i.ModelName,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CacheHitTokens,
			&i.CacheMissTokens,
			&i.AmountCents,
			&i.LogType,
			&i.PreDeductedCents,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelFailureLogsByChannel = `-- name: ListChannelFailureLogsByChannel :many
SELECT
    id,
    channel_id,
    request_id,
    model_name,
    provider,
    upstream_base_url,
    error_type,
    status_code,
    response_body,
    error_message,
    latency_ms,
    circuit_state,
    created_at
FROM channel_failure_logs
WHERE channel_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListChannelFailureLogsByChannelParams struct {
	ChannelID int32
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) ListChannelFailureLogsByChannel(ctx context.Context, arg ListChannelFailureLogsByChannelParams) ([]ChannelFailureLog, error) {
	rows, err := q.db.Query(ctx, listChannelFailureLogsByChannel, arg.ChannelID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelFailureLog
	for rows.Next() {
		var i ChannelFailureLog
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.RequestID,
			&i.ModelName,
			&i.Provider,
			&i.UpstreamBaseUrl,
			&i.ErrorType,
			&i.StatusCode,
			&i.ResponseBody,
			&i.ErrorMessage,
			&i.LatencyMs,
			&i.CircuitState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForAdmin = `-- name: ListUsersForAdmin :many
WITH user_usage AS (
    SELECT
        user_id,
        COUNT(*)::bigint AS total_requests,
        COALESCE(SUM(prompt_tokens), 0)::bigint AS total_prompt_tokens,
        COALESCE(SUM(completion_tokens), 0)::bigint AS total_completion_tokens,
        COALESCE(SUM(amount_cents), 0)::bigint AS total_amount_cents,
        MAX(created_at) AS last_request_at
    FROM billing_logs
    GROUP BY user_id
),
active_keys AS (
    SELECT
        user_id,
        COUNT(*) FILTER (WHERE status = 1)::bigint AS active_key_count
    FROM api_keys
    GROUP BY user_id
)
SELECT
    u.id,
    u.email,
    COALESCE(u.nickname, '') AS nickname,
    u.cash_balance,
    u.grant_balance,
    u.status,
    u.created_at,
    u.last_login_at,
    COALESCE(user_usage.total_requests, 0)::bigint AS total_requests,
    COALESCE(user_usage.total_prompt_tokens, 0)::bigint AS total_prompt_tokens,
    COALESCE(user_usage.total_completion_tokens, 0)::bigint AS total_completion_tokens,
    COALESCE(user_usage.total_amount_cents, 0)::bigint AS total_amount_cents,
    user_usage.last_request_at,
    COALESCE(active_keys.active_key_count, 0)::bigint AS active_key_count
FROM users u
LEFT JOIN user_usage ON user_usage.user_id = u.id
LEFT JOIN active_keys ON active_keys.user_id = u.id
WHERE
    (
        $1::text = ''
        OR u.email ILIKE '%' || $1::text || '%'
        OR COALESCE(u.nickname, '') ILIKE '%' || $1::text || '%'
    )
ORDER BY COALESCE(user_usage.last_request_at, u.created_at) DESC, u.id DESC
LIMIT $3
OFFSET $2
`

type ListUsersForAdminParams struct {
	Keyword   string
	OffsetVal int32
	LimitVal  int32
}

type ListUsersForAdminRow struct {
	ID                    int32
	Email                 string
	Nickname              string
	CashBalance           pgtype.Int8
	GrantBalance          pgtype.Int8
	Status                pgtype.Int4
	CreatedAt             pgtype.Timestamptz
	LastLoginAt           pgtype.Timestamptz
	TotalRequests         int64
	TotalPromptTokens     int64
	TotalCompletionTokens int64
	TotalAmountCents      int64
	LastRequestAt         interface{}
	ActiveKeyCount        int64
}

func (q *Queries) ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersForAdmin, arg.Keyword, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersForAdminRow
	for rows.Next() {
		var i ListUsersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Nickname,
			&i.CashBalance,
			&i.GrantBalance,
			&i.Status,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.TotalRequests,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.TotalAmountCents,
			&i.LastRequestAt,
			&i.ActiveKeyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsyncTaskStatus = `-- name: MarkAsyncTaskStatus :one
UPDATE async_tasks
SET
    status = $2,
    output_payload = $3,
    error_payload = $4,
    metadata = $5,
    actual_cost_cents = $6,
    updated_at = NOW(),
    finished_at = CASE
        WHEN $2 IN ('succeeded', 'failed', 'canceled') THEN NOW()
        ELSE finished_at
    END,
    canceled_at = CASE
        WHEN $2 = 'canceled' THEN NOW()
        ELSE canceled_at
    END
WHERE
    id = $1 RETURNING id, user_id, channel_id, request_id, task_type, provider, model_name, status, upstream_task_id, input_payload, output_payload, error_payload, metadata, pre_deducted_cents, grant_deducted, cash_deducted, actual_cost_cents, created_at, updated_at, submitted_at, finished_at, canceled_at, sub_deducted
`

type MarkAsyncTaskStatusParams struct {
	ID              string
	Status          string
	OutputPayload   []byte
	ErrorPayload    []byte
	Metadata        []byte
	ActualCostCents int64
}

func (q *Queries) MarkAsyncTaskStatus(ctx context.Context, arg MarkAsyncTaskStatusParams) (AsyncTask, error) {
	row := q.db.QueryRow(ctx, markAsyncTaskStatus,
		arg.ID,
		arg.Status,
		arg.OutputPayload,
		arg.ErrorPayload,
		arg.Metadata,
		arg.ActualCostCents,
	)
	var i AsyncTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.RequestID,
		&i.TaskType,
		&i.Provider,
		&i.ModelName,
		&i.Status,
		&i.UpstreamTaskID,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ErrorPayload,
		&i.Metadata,
		&i.PreDeductedCents,
		&i.GrantDeducted,
		&i.CashDeducted,
		&i.ActualCostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.FinishedAt,
		&i.CanceledAt,
		&i.SubDeducted,
	)
	return i, err
}

const markAsyncTaskSubmitted = `-- name: MarkAsyncTaskSubmitted :one
UPDATE async_tasks
SET
    channel_id = $2,
    provider = $3,
    status = $4,
    upstream_task_id = $5,
    output_payload = $6,
    metadata = $7,
    submitted_at = NOW(),
    updated_at = NOW()
WHERE
    id = $1 RETURNING id, user_id, channel_id, request_id, task_type, provider, model_name, status, upstream_task_id, input_payload, output_payload, error_payload, metadata, pre_deducted_cents, grant_deducted, cash_deducted, actual_cost_cents, created_at, updated_at, submitted_at, finished_at, canceled_at, sub_deducted
`

type MarkAsyncTaskSubmittedParams struct {
	ID             string
	ChannelID      pgtype.Int4
	Provider       string
	Status         string
	UpstreamTaskID pgtype.Text
	OutputPayload  []byte
	Metadata       []byte
}

func (q *Queries) MarkAsyncTaskSubmitted(ctx context.Context, arg MarkAsyncTaskSubmittedParams) (AsyncTask, error) {
	row := q.db.QueryRow(ctx, markAsyncTaskSubmitted,
		arg.ID,
		arg.ChannelID,
		arg.Provider,
		arg.Status,
		arg.UpstreamTaskID,
		arg.OutputPayload,
		arg.Metadata,
	)
	var i AsyncTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.RequestID,
		&i.TaskType,
		&i.Provider,
		&i.ModelName,
		&i.Status,
		&i.UpstreamTaskID,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ErrorPayload,
		&i.Metadata,
		&i.PreDeductedCents,
		&i.GrantDeducted,
		&i.CashDeducted,
		&i.ActualCostCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.FinishedAt,
		&i.CanceledAt,
		&i.SubDeducted,
	)
	return i, err
}

const rotateAPIKey = `-- name: RotateAPIKey :exec
UPDATE api_keys SET key_string = $1 WHERE id = $2 AND user_id = $3
`

type RotateAPIKeyParams struct {
	KeyString string
	ID        int32
	UserID    pgtype.Int4
}

func (q *Queries) RotateAPIKey(ctx context.Context, arg RotateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, rotateAPIKey, arg.KeyString, arg.ID, arg.UserID)
	return err
}

const setSubscriptionFields = `-- name: SetSubscriptionFields :exec
UPDATE users
SET
    grant_balance = $2,
    sub_expires_at = $3,
    tier_level = $4
WHERE
    id = $1
`

type SetSubscriptionFieldsParams struct {
	ID           int32
	GrantBalance pgtype.Int8
	SubExpiresAt pgtype.Timestamptz
	TierLevel    pgtype.Int4
}

func (q *Queries) SetSubscriptionFields(ctx context.Context, arg SetSubscriptionFieldsParams) error {
	_, err := q.db.Exec(ctx, setSubscriptionFields,
		arg.ID,
		arg.GrantBalance,
		arg.SubExpiresAt,
		arg.TierLevel,
	)
	return err
}

const updateAPIKeyName = `-- name: UpdateAPIKeyName :exec
UPDATE api_keys SET name = $1 WHERE id = $2 AND user_id = $3
`

type UpdateAPIKeyNameParams struct {
	Name   string
	ID     int32
	UserID pgtype.Int4
}

func (q *Queries) UpdateAPIKeyName(ctx context.Context, arg UpdateAPIKeyNameParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyName, arg.Name, arg.ID, arg.UserID)
	return err
}

const updateAPIKeyStatus = `-- name: UpdateAPIKeyStatus :exec
UPDATE api_keys SET status = $1 WHERE id = $2 AND user_id = $3
`

type UpdateAPIKeyStatusParams struct {
	Status pgtype.Int4
	ID     int32
	UserID pgtype.Int4
}

func (q *Queries) UpdateAPIKeyStatus(ctx context.Context, arg UpdateAPIKeyStatusParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyStatus, arg.Status, arg.ID, arg.UserID)
	return err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET
    name = $2,
    provider = $3,
    base_url = $4,
    api_key = $5,
    weight = $6,
    models = $7,
    protocol_type = $8,
    upload_mode = $9,
    model_mapping = $10,
    supports_async = $11,
    status = $12
WHERE
    id = $1 RETURNING id, name, provider, base_url, api_key, models, protocol_type, upload_mode, model_mapping, supports_async, weight, status
`

type UpdateChannelParams struct {
	ID            int32
	Name          string
	Provider      string
	BaseUrl       string
	ApiKey        string
	Weight        pgtype.Int4
	Models        string
	ProtocolType  string
	UploadMode    string
	ModelMapping  []byte
	SupportsAsync bool
	Status        pgtype.Int4
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Provider,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Weight,
		arg.Models,
		arg.ProtocolType,
		arg.UploadMode,
		arg.ModelMapping,
		arg.SupportsAsync,
		arg.Status,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ProtocolType,
		&i.UploadMode,
		&i.ModelMapping,
		&i.SupportsAsync,
		&i.Weight,
		&i.Status,
	)
	return i, err
}

const updateChannelStatus = `-- name: UpdateChannelStatus :exec
UPDATE channels SET status = $2 WHERE id = $1
`

type UpdateChannelStatusParams struct {
	ID     int32
	Status pgtype.Int4
}

func (q *Queries) UpdateChannelStatus(ctx context.Context, arg UpdateChannelStatusParams) error {
	_, err := q.db.Exec(ctx, updateChannelStatus, arg.ID, arg.Status)
	return err
}

const updateModel = `-- name: UpdateModel :one
UPDATE models
SET
    input_price_cents = $2,
    output_price_cents = $3,
    cache_hit_price_cents = $4,
    cache_miss_price_cents = $5,
    multiplier = $6,
    billing_policy = $7,
    modality = $8,
    pricing_mode = $9,
    pricing_config = $10,
    max_concurrency = $11,
    status = $12
WHERE
    model_name = $1 RETURNING
    id,
    model_name,
    input_price_cents,
    output_price_cents,
    cache_hit_price_cents,
    cache_miss_price_cents,
    multiplier,
    billing_policy,
    modality,
    pricing_mode,
    pricing_config,
    max_concurrency,
    status
`

type UpdateModelParams struct {
	ModelName           string
	InputPriceCents     int64
	OutputPriceCents    int64
	CacheHitPriceCents  int64
	CacheMissPriceCents int64
	Multiplier          float32
	BillingPolicy       string
	Modality            string
	PricingMode         string
	PricingConfig       []byte
	MaxConcurrency      int32
	Status              pgtype.Int4
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, updateModel,
		arg.ModelName,
		arg.InputPriceCents,
		arg.OutputPriceCents,
		arg.CacheHitPriceCents,
		arg.CacheMissPriceCents,
		arg.Multiplier,
		arg.BillingPolicy,
		arg.Modality,
		arg.PricingMode,
		arg.PricingConfig,
		arg.MaxConcurrency,
		arg.Status,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ModelName,
		&i.InputPriceCents,
		&i.OutputPriceCents,
		&i.CacheHitPriceCents,
		&i.CacheMissPriceCents,
		&i.Multiplier,
		&i.BillingPolicy,
		&i.Modality,
		&i.PricingMode,
		&i.PricingConfig,
		&i.MaxConcurrency,
		&i.Status,
	)
	return i, err
}

const updateUserGrantBalance = `-- name: UpdateUserGrantBalance :exec
UPDATE users
SET
    grant_balance = grant_balance + $2,
    sub_expires_at = CASE
        WHEN sub_expires_at IS NULL AND $2 > 0 THEN NOW() + INTERVAL '30 days'
        ELSE sub_expires_at
    END
WHERE
    id = $1
`

type UpdateUserGrantBalanceParams struct {
	ID           int32
	GrantBalance pgtype.Int8
}

func (q *Queries) UpdateUserGrantBalance(ctx context.Context, arg UpdateUserGrantBalanceParams) error {
	_, err := q.db.Exec(ctx, updateUserGrantBalance, arg.ID, arg.GrantBalance)
	return err
}

const updateUserTopupBalance = `-- name: UpdateUserTopupBalance :exec
UPDATE users
SET
    cash_balance = cash_balance + $2
WHERE
    id = $1
`

type UpdateUserTopupBalanceParams struct {
	ID          int32
	CashBalance pgtype.Int8
}

func (q *Queries) UpdateUserTopupBalance(ctx context.Context, arg UpdateUserTopupBalanceParams) error {
	_, err := q.db.Exec(ctx, updateUserTopupBalance, arg.ID, arg.CashBalance)
	return err
}
